import { ComponentTheme } from '../../../packages/components/src/theme'
import { VariantsProps } from './contract'

export type VariantsTheme = {
  primary_focus: string,
  secondary_focus: string,
  success_focus: string,
  warning_focus: string,
  error_focus: string,

  contrast_color_normal: string,
  contrast_color_hover: string,
  contrast_color_active: string,
  contrast_color_checked: string,
  contrast_color_focus: string,
  contrast_color_disabled: string,

  contrast_light_color_normal: string,
  contrast_light_color_hover: string,
  contrast_light_color_active: string,
  contrast_light_color_checked: string,
  contrast_light_color_focus: string,
  contrast_light_color_disabled: string,

  primary_color_normal: string,
  primary_color_hover: string,
  primary_color_active: string,
  primary_color_checked: string,
  primary_color_focus: string,
  primary_color_disabled: string,

  secondary_color_normal: string,
  secondary_color_hover: string,
  secondary_color_active: string,
  secondary_color_checked: string,
  secondary_color_focus: string,
  secondary_color_disabled: string,

  success_color_normal: string,
  success_color_hover: string,
  success_color_active: string,
  success_color_checked: string,
  success_color_focus: string,
  success_color_disabled: string,

  warning_color_normal: string,
  warning_color_hover: string,
  warning_color_active: string,
  warning_color_checked: string,
  warning_color_focus: string,
  warning_color_disabled: string,

  error_color_normal: string,
  error_color_hover: string,
  error_color_active: string,
  error_color_checked: string,
  error_color_focus: string,
  error_color_disabled: string,


  contrast_borderColor_normal: string,
  contrast_borderColor_hover: string,
  contrast_borderColor_active: string,
  contrast_borderColor_checked: string,
  contrast_borderColor_focus: string,
  contrast_borderColor_disabled: string,

  contrast_light_borderColor_normal: string,
  contrast_light_borderColor_hover: string,
  contrast_light_borderColor_active: string,
  contrast_light_borderColor_checked: string,
  contrast_light_borderColor_focus: string,
  contrast_light_borderColor_disabled: string,

  gray_borderColor_normal: string,
  gray_borderColor_hover: string,
  gray_borderColor_active: string,
  gray_borderColor_checked: string,
  gray_borderColor_focus: string,
  gray_borderColor_disabled: string,

  primary_borderColor_normal: string,
  primary_borderColor_hover: string,
  primary_borderColor_active: string,
  primary_borderColor_checked: string,
  primary_borderColor_focus: string,
  primary_borderColor_disabled: string,

  secondary_borderColor_normal: string,
  secondary_borderColor_hover: string,
  secondary_borderColor_active: string,
  secondary_borderColor_checked: string,
  secondary_borderColor_focus: string,
  secondary_borderColor_disabled: string,

  success_borderColor_normal: string,
  success_borderColor_hover: string,
  success_borderColor_active: string,
  success_borderColor_checked: string,
  success_borderColor_focus: string,
  success_borderColor_disabled: string,

  warning_borderColor_normal: string,
  warning_borderColor_hover: string,
  warning_borderColor_active: string,
  warning_borderColor_checked: string,
  warning_borderColor_focus: string,
  warning_borderColor_disabled: string,

  error_borderColor_normal: string,
  error_borderColor_hover: string,
  error_borderColor_active: string,
  error_borderColor_checked: string,
  error_borderColor_focus: string,
  error_borderColor_disabled: string,


  contrast_backgroundColor_normal: string,
  contrast_backgroundColor_hover: string,
  contrast_backgroundColor_active: string,
  contrast_backgroundColor_checked: string,
  contrast_backgroundColor_focus: string,
  contrast_backgroundColor_disabled: string,

  contrast_light_backgroundColor_normal: string,
  contrast_light_backgroundColor_hover: string,
  contrast_light_backgroundColor_active: string,
  contrast_light_backgroundColor_checked: string,
  contrast_light_backgroundColor_focus: string,
  contrast_light_backgroundColor_disabled: string,

  gray_backgroundColor_normal: string,
  gray_backgroundColor_hover: string,
  gray_backgroundColor_active: string,
  gray_backgroundColor_checked: string,
  gray_backgroundColor_focus: string,
  gray_backgroundColor_disabled: string,

  primary_backgroundColor_normal: string,
  primary_backgroundColor_hover: string,
  primary_backgroundColor_active: string,
  primary_backgroundColor_checked: string,
  primary_backgroundColor_focus: string,
  primary_backgroundColor_disabled: string,

  secondary_backgroundColor_normal: string,
  secondary_backgroundColor_hover: string,
  secondary_backgroundColor_active: string,
  secondary_backgroundColor_checked: string,
  secondary_backgroundColor_focus: string,
  secondary_backgroundColor_disabled: string,

  success_backgroundColor_normal: string,
  success_backgroundColor_hover: string,
  success_backgroundColor_active: string,
  success_backgroundColor_checked: string,
  success_backgroundColor_focus: string,
  success_backgroundColor_disabled: string,

  warning_backgroundColor_normal: string,
  warning_backgroundColor_hover: string,
  warning_backgroundColor_active: string,
  warning_backgroundColor_checked: string,
  warning_backgroundColor_focus: string,
  warning_backgroundColor_disabled: string,

  error_backgroundColor_normal: string,
  error_backgroundColor_hover: string,
  error_backgroundColor_active: string,
  error_backgroundColor_checked: string,
  error_backgroundColor_focus: string,
  error_backgroundColor_disabled: string,
}

export const variantsTheme: ComponentTheme<VariantsTheme> = ({ palette, variants }, override) => {
  const { primary, secondary, success, warning, error } = variants

  const focus = {
    primary_focus: palette.blue30,
    secondary_focus: palette.blue30,
    success_focus: palette[`${success}30`],
    warning_focus: palette[`${warning}30`],
    error_focus: palette[`${error}30`],
  }

  const color = {
    contrast_color_normal: palette.black,
    contrast_color_hover: palette.black,
    contrast_color_active: palette.black,
    contrast_color_checked: palette.black,
    contrast_color_focus: palette.black,
    contrast_color_disabled: palette.gray50,

    contrast_light_color_normal: palette.white,
    contrast_light_color_hover: palette.white,
    contrast_light_color_active: palette.white,
    contrast_light_color_checked: palette.white,
    contrast_light_color_focus: palette.white,
    contrast_light_color_disabled: palette.white,

    primary_color_normal: palette[`${primary}50`],
    primary_color_hover: palette[`${primary}70`],
    primary_color_active: palette[`${primary}80`],
    primary_color_checked: palette[`${primary}80`],
    primary_color_focus: palette[`${primary}80`],
    primary_color_disabled: palette[`${primary}20`],

    secondary_color_normal: palette[`${secondary}60`],
    secondary_color_hover: palette[`${secondary}80`],
    secondary_color_active: palette[`${secondary}80`],
    secondary_color_checked: palette[`${secondary}80`],
    secondary_color_focus: palette[`${secondary}80`],
    secondary_color_disabled: palette[`${secondary}30`],

    success_color_normal: palette[`${success}50`],
    success_color_hover: palette[`${success}70`],
    success_color_active: palette[`${success}80`],
    success_color_checked: palette[`${success}80`],
    success_color_focus: palette[`${success}80`],
    success_color_disabled: palette[`${success}20`],

    warning_color_normal: palette[`${warning}50`],
    warning_color_hover: palette[`${warning}70`],
    warning_color_active: palette[`${warning}80`],
    warning_color_checked: palette[`${warning}80`],
    warning_color_focus: palette[`${warning}80`],
    warning_color_disabled: palette[`${warning}20`],

    error_color_normal: palette[`${error}40`],
    error_color_hover: palette[`${error}60`],
    error_color_active: palette[`${error}70`],
    error_color_checked: palette[`${error}70`],
    error_color_focus: palette[`${error}70`],
    error_color_disabled: palette[`${error}20`],
  }

  const border = {
    contrast_borderColor_normal: palette.gray40,
    contrast_borderColor_hover: palette.gray50,
    contrast_borderColor_active: palette.gray50,
    contrast_borderColor_checked: palette.gray50,
    contrast_borderColor_focus: palette.gray60,
    contrast_borderColor_disabled: palette.gray20,

    contrast_light_borderColor_normal: palette.gray40,
    contrast_light_borderColor_hover: palette.gray50,
    contrast_light_borderColor_active: palette.gray50,
    contrast_light_borderColor_checked: palette.gray50,
    contrast_light_borderColor_focus: palette.gray60,
    contrast_light_borderColor_disabled: palette.gray20,

    primary_borderColor_normal: palette[`${primary}40`],
    primary_borderColor_hover: palette[`${primary}50`],
    primary_borderColor_active: palette[`${primary}60`],
    primary_borderColor_checked: palette[`${primary}60`],
    primary_borderColor_focus: palette[`${primary}60`],
    primary_borderColor_disabled: palette[`${primary}20`],

    secondary_borderColor_normal: palette[`${secondary}40`],
    secondary_borderColor_hover: palette[`${secondary}50`],
    secondary_borderColor_active: palette[`${secondary}60`],
    secondary_borderColor_checked: palette[`${secondary}60`],
    secondary_borderColor_focus: palette[`${secondary}60`],
    secondary_borderColor_disabled: palette[`${secondary}20`],

    success_borderColor_normal: palette[`${success}50`],
    success_borderColor_hover: palette[`${success}60`],
    success_borderColor_active: palette[`${success}70`],
    success_borderColor_checked: palette[`${success}70`],
    success_borderColor_focus: palette[`${success}70`],
    success_borderColor_disabled: palette[`${success}20`],

    warning_borderColor_normal: palette[`${warning}40`],
    warning_borderColor_hover: palette[`${warning}50`],
    warning_borderColor_active: palette[`${warning}60`],
    warning_borderColor_checked: palette[`${warning}60`],
    warning_borderColor_focus: palette[`${warning}60`],
    warning_borderColor_disabled: palette[`${warning}20`],

    error_borderColor_normal: palette[`${error}40`],
    error_borderColor_hover: palette[`${error}50`],
    error_borderColor_active: palette[`${error}60`],
    error_borderColor_checked: palette[`${error}60`],
    error_borderColor_focus: palette[`${error}60`],
    error_borderColor_disabled: palette[`${error}20`],
  }

  const background = {
    contrast_backgroundColor_normal: palette.gray20,
    contrast_backgroundColor_hover: palette.gray30,
    contrast_backgroundColor_active: palette.gray40,
    contrast_backgroundColor_checked: palette.gray40,
    contrast_backgroundColor_focus: palette.gray20,
    contrast_backgroundColor_disabled: palette.gray40,

    contrast_light_backgroundColor_normal: palette.white,
    contrast_light_backgroundColor_hover: palette.gray10,
    contrast_light_backgroundColor_active: palette.gray20,
    contrast_light_backgroundColor_checked: palette.gray20,
    contrast_light_backgroundColor_focus: palette.gray20,
    contrast_light_backgroundColor_disabled: palette.gray10,

    primary_backgroundColor_normal: palette[`${primary}40`],
    primary_backgroundColor_hover: palette[`${primary}50`],
    primary_backgroundColor_active: palette[`${primary}60`],
    primary_backgroundColor_checked: palette[`${primary}60`],
    primary_backgroundColor_focus: palette[`${primary}60`],
    primary_backgroundColor_disabled: palette[`${primary}20`],

    secondary_backgroundColor_normal: palette[`${secondary}20`],
    secondary_backgroundColor_hover: palette[`${secondary}30`],
    secondary_backgroundColor_active: palette[`${secondary}40`],
    secondary_backgroundColor_checked: palette[`${secondary}40`],
    secondary_backgroundColor_focus: palette[`${secondary}40`],
    secondary_backgroundColor_disabled: palette[`${secondary}10`],

    success_backgroundColor_normal: palette[`${success}50`],
    success_backgroundColor_hover: palette[`${success}60`],
    success_backgroundColor_active: palette[`${success}70`],
    success_backgroundColor_checked: palette[`${success}70`],
    success_backgroundColor_focus: palette[`${success}70`],
    success_backgroundColor_disabled: palette[`${success}20`],

    warning_backgroundColor_normal: palette[`${warning}40`],
    warning_backgroundColor_hover: palette[`${warning}50`],
    warning_backgroundColor_active: palette[`${warning}60`],
    warning_backgroundColor_checked: palette[`${warning}60`],
    warning_backgroundColor_focus: palette[`${warning}60`],
    warning_backgroundColor_disabled: palette[`${warning}20`],

    error_backgroundColor_normal: palette[`${error}40`],
    error_backgroundColor_hover: palette[`${error}50`],
    error_backgroundColor_active: palette[`${error}60`],
    error_backgroundColor_checked: palette[`${error}60`],
    error_backgroundColor_focus: palette[`${error}60`],
    error_backgroundColor_disabled: palette[`${error}20`],
  }

  return {
    ...focus,
    ...color,
    ...border,
    ...background,
    ...override,
  } as VariantsTheme
}
