import React from 'react';
export declare const Radio: <T extends object>(props: Pick<import("../Toggle").ToggleProps, "disabled" | "loading" | "label" | "size" | "height" | "maxHeight" | "maxWidth" | "minHeight" | "minWidth" | "width" | "m" | "shape" | "shrink" | "grow" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "align" | "valignSelf" | "valign" | "variant" | "value" | "name" | "onChange" | "checked" | "description" | "labelPosition" | "id" | "tabIndex" | "onClick" | "onMouseEnter" | "onMouseLeave" | "onKeyDown"> & {
    override?: import("../..").DeepPartial<{
        defaultProps?: Partial<Pick<import("../Toggle").ToggleProps, "disabled" | "loading" | "label" | "size" | "height" | "maxHeight" | "maxWidth" | "minHeight" | "minWidth" | "width" | "m" | "shape" | "shrink" | "grow" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "align" | "valignSelf" | "valign" | "variant" | "value" | "name" | "onChange" | "checked" | "description" | "labelPosition" | "id" | "tabIndex" | "onClick" | "onMouseEnter" | "onMouseLeave" | "onKeyDown">> | undefined;
        mapProps?: ((props: Pick<import("../Toggle").ToggleProps, "disabled" | "loading" | "label" | "size" | "height" | "maxHeight" | "maxWidth" | "minHeight" | "minWidth" | "width" | "m" | "shape" | "shrink" | "grow" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "align" | "valignSelf" | "valign" | "variant" | "value" | "name" | "onChange" | "checked" | "description" | "labelPosition" | "id" | "tabIndex" | "onClick" | "onMouseEnter" | "onMouseLeave" | "onKeyDown">) => Partial<Pick<import("../Toggle").ToggleProps, "disabled" | "loading" | "label" | "size" | "height" | "maxHeight" | "maxWidth" | "minHeight" | "minWidth" | "width" | "m" | "shape" | "shrink" | "grow" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "align" | "valignSelf" | "valign" | "variant" | "value" | "name" | "onChange" | "checked" | "description" | "labelPosition" | "id" | "tabIndex" | "onClick" | "onMouseEnter" | "onMouseLeave" | "onKeyDown">>) | undefined;
        scheme: {
            Toggle?: import("../..").SchemeType<Pick<import("../Toggle").ToggleProps, "disabled" | "loading" | "label" | "size" | "height" | "maxHeight" | "maxWidth" | "minHeight" | "minWidth" | "width" | "m" | "shape" | "shrink" | "grow" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "align" | "valignSelf" | "valign" | "variant" | "value" | "name" | "onChange" | "checked" | "description" | "labelPosition" | "id" | "tabIndex" | "onClick" | "onMouseEnter" | "onMouseLeave" | "onKeyDown">, never, {}> | undefined;
            Switch?: import("../..").SchemeType<Pick<import("../Toggle").ToggleProps, "disabled" | "loading" | "label" | "size" | "height" | "maxHeight" | "maxWidth" | "minHeight" | "minWidth" | "width" | "m" | "shape" | "shrink" | "grow" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "align" | "valignSelf" | "valign" | "variant" | "value" | "name" | "onChange" | "checked" | "description" | "labelPosition" | "id" | "tabIndex" | "onClick" | "onMouseEnter" | "onMouseLeave" | "onKeyDown">, never, {}> | undefined;
            Icon?: import("../..").SchemeType<Pick<import("../Toggle").ToggleProps, "disabled" | "loading" | "label" | "size" | "height" | "maxHeight" | "maxWidth" | "minHeight" | "minWidth" | "width" | "m" | "shape" | "shrink" | "grow" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "align" | "valignSelf" | "valign" | "variant" | "value" | "name" | "onChange" | "checked" | "description" | "labelPosition" | "id" | "tabIndex" | "onClick" | "onMouseEnter" | "onMouseLeave" | "onKeyDown">, import("../Icon").IconProps, {}> | undefined;
            Label?: import("../..").SchemeType<Pick<import("../Toggle").ToggleProps, "disabled" | "loading" | "label" | "size" | "height" | "maxHeight" | "maxWidth" | "minHeight" | "minWidth" | "width" | "m" | "shape" | "shrink" | "grow" | "mx" | "my" | "mt" | "mr" | "mb" | "ml" | "align" | "valignSelf" | "valign" | "variant" | "value" | "name" | "onChange" | "checked" | "description" | "labelPosition" | "id" | "tabIndex" | "onClick" | "onMouseEnter" | "onMouseLeave" | "onKeyDown">, import("../Text").TextProps, {}> | undefined;
        };
    }> | undefined;
    ref?: ((instance: HTMLElement | null) => void) | React.RefObject<HTMLElement> | null | undefined;
} & T) => JSX.Element;
